import * as fs from "node:fs";
import path from "path";

const emojiMap = {
    // Smileys & Emotion
    'smile': '😄',
    'grin': '😁',
    'joy': '😂',
    'rofl': '🤣',
    'smiley': '😃',
    'sweat_smile': '😅',
    'laughing': '😆',
    'wink': '😉',
    'blush': '😊',
    'yum': '😋',
    'heart_eyes': '😍',
    'kissing_heart': '😘',
    'kissing': '😗',
    'relaxed': '☺️',
    'slightly_smiling_face': '🙂',
    'hugging_face': '🤗',
    'thinking_face': '🤔',
    'neutral_face': '😐',
    'expressionless': '😑',
    'no_mouth': '😶',
    'smirk': '😏',
    'unamused': '😒',
    'grimacing': '😬',
    'lying_face': '🤥',
    'relieved': '😌',
    'pensive': '😔',
    'sleepy': '😪',
    'drooling_face': '🤤',
    'sleeping': '😴',
    'mask': '😷',
    'face_with_thermometer': '🤒',
    'face_with_head_bandage': '🤕',
    'nauseated_face': '🤢',
    'sneezing_face': '🤧',
    'dizzy_face': '😵',
    'zipper_mouth_face': '🤐',
    'cowboy_hat_face': '🤠',
    'money_mouth_face': '🤑',
    'nerd_face': '🤓',
    'sob': '😭',
    'cry': '😢',
    'sunglasses': '😎',
    'clown_face': '🤡',
    'innocent': '😇',
    'smiling_imp': '😈',
    'imp': '👿',
    'skull': '💀',
    'skull_and_crossbones': '☠️',
    'hankey': '💩',
    'poop': '💩',
    'shit': '💩',
    'ghost': '👻',
    'alien': '👽',
    'robot_face': '🤖',
    'smiley_cat': '😺',
    'smile_cat': '😸',
    'joy_cat': '😹',
    'heart_eyes_cat': '😻',
    'smirk_cat': '😼',
    'kissing_cat': '😽',
    'scream_cat': '🙀',
    'crying_cat_face': '😿',
    'pouting_cat': '😾',

    // Gestures & Body Parts
    'wave': '👋',
    'raised_back_of_hand': '🤚',
    'raised_hand_with_fingers_splayed': '🖐️',
    'hand': '✋',
    'vulcan_salute': '🖖',
    'ok_hand': '👌',
    'pinching_hand': '🤏',
    'v': '✌️',
    'crossed_fingers': '🤞',
    'i_love_you_hand_sign': '🤟',
    'the_horns': '🤘',
    'call_me_hand': '🤙',
    'point_left': '👈',
    'point_right': '👉',
    'point_up_2': '👆',
    'point_down': '👇',
    'point_up': '☝️',
    '+1': '👍',
    'thumbsup': '👍',
    '-1': '👎',
    'thumbsdown': '👎',
    'fist': '✊',
    'facepunch': '👊',
    'punch': '👊',
    'left_facing_fist': '🤛',
    'right_facing_fist': '🤜',
    'clap': '👏',
    'raised_hands': '🙌',
    'open_hands': '👐',
    'palms_up_together': '🤲',
    'handshake': '🤝',
    'pray': '🙏',
    'writing_hand': '✍️',
    'muscle': '💪',
    'leg': '🦵',
    'foot': '🦶',
    'ear': '👂',
    'nose': '👃',
    'brain': '🧠',
    'tooth': '🦷',
    'bone': '🦴',
    'eyes': '👀',
    'eye': '👁️',
    'tongue': '👅',
    'lips': '👄',

    // People
    'baby': '👶',
    'child': '🧒',
    'boy': '👦',
    'girl': '👧',
    'adult': '🧑',
    'man': '👨',
    'woman': '👩',
    'older_adult': '🧓',
    'older_man': '👴',
    'older_woman': '👵',

    // Animals & Nature
    'dog': '🐶',
    'cat': '🐱',
    'mouse': '🐭',
    'hamster': '🐹',
    'rabbit': '🐰',
    'fox_face': '🦊',
    'bear': '🐻',
    'panda_face': '🐼',
    'koala': '🐨',
    'tiger': '🐯',
    'lion_face': '🦁',
    'cow': '🐮',
    'pig': '🐷',
    'pig_nose': '🐽',
    'frog': '🐸',
    'monkey_face': '🐵',
    'see_no_evil': '🙈',
    'hear_no_evil': '🙉',
    'speak_no_evil': '🙊',
    'monkey': '🐒',
    'chicken': '🐔',
    'penguin': '🐧',
    'bird': '🐦',
    'baby_chick': '🐤',
    'hatching_chick': '🐣',
    'hatched_chick': '🐥',
    'duck': '🦆',
    'eagle': '🦅',
    'owl': '🦉',
    'bat': '🦇',
    'wolf': '🐺',
    'boar': '🐗',
    'horse': '🐴',
    'unicorn_face': '🦄',
    'bee': '🐝',
    'bug': '🐛',
    'butterfly': '🦋',
    'snail': '🐌',
    'shell': '🐚',
    'beetle': '🐞',
    'ant': '🐜',
    'spider': '🕷️',
    'spider_web': '🕸️',
    'turtle': '🐢',
    'snake': '🐍',
    'lizard': '🦎',
    'scorpion': '🦂',
    'crab': '🦀',
    'squid': '🦑',
    'octopus': '🐙',
    'shrimp': '🦐',
    'tropical_fish': '🐠',
    'fish': '🐟',
    'blowfish': '🐡',
    'dolphin': '🐬',
    'shark': '🦈',
    'whale': '🐳',
    'whale2': '🐋',
    'crocodile': '🐊',
    'tiger2': '🐅',
    'leopard': '🐆',
    'zebra': '🦓',
    'gorilla': '🦍',
    'elephant': '🐘',
    'rhino': '🦏',
    'hippopotamus': '🦛',
    'camel': '🐪',
    'giraffe': '🦒',
    'kangaroo': '🦘',
    'deer': '🦌',
    'dog2': '🐕',
    'poodle': '🐩',
    'cat2': '🐈',
    'rooster': '🐓',
    'turkey': '🦃',
    'dove_of_peace': '🕊️',
    'rabbit2': '🐇',
    'mouse2': '🐁',
    'rat': '🐀',
    'chipmunk': '🐿️',
    'hedgehog': '🦔',
    'feet': '🐾',
    'dragon': '🐉',
    'dragon_face': '🐲',
    'cactus': '🌵',
    'christmas_tree': '🎄',
    'evergreen_tree': '🌲',
    'deciduous_tree': '🌳',
    'palm_tree': '🌴',
    'seedling': '🌱',
    'herb': '🌿',
    'shamrock': '☘️',
    'four_leaf_clover': '🍀',
    'bamboo': '🎍',
    'tanabata_tree': '🎋',
    'leaves': '🍃',
    'fallen_leaf': '🍂',
    'maple_leaf': '🍁',
    'mushroom': '🍄',
    'ear_of_rice': '🌾',
    'bouquet': '💐',
    'tulip': '🌷',
    'rose': '🌹',
    'wilted_flower': '🥀',
    'sunflower': '🌻',
    'blossom': '🌼',
    'cherry_blossom': '🌸',
    'hibiscus': '🌺',
    'earth_americas': '🌎',
    'earth_africa': '🌍',
    'earth_asia': '🌏',
    'full_moon': '🌕',
    'waning_gibbous_moon': '🌖',
    'last_quarter_moon': '🌗',
    'waning_crescent_moon': '🌘',
    'new_moon': '🌑',
    'waxing_crescent_moon': '🌒',
    'first_quarter_moon': '🌓',
    'waxing_gibbous_moon': '🌔',
    'new_moon_with_face': '🌚',
    'full_moon_with_face': '🌝',
    'sun_with_face': '🌞',
    'first_quarter_moon_with_face': '🌛',
    'last_quarter_moon_with_face': '🌜',
    'crescent_moon': '🌙',
    'dizzy': '💫',
    'star': '⭐',
    'star2': '🌟',
    'sparkles': '✨',
    'zap': '⚡',
    'fire': '🔥',
    'boom': '💥',
    'comet': '☄️',
    'sunny': '☀️',
    'partly_sunny': '⛅',
    'cloud': '☁️',
    'rain_cloud': '🌧️',
    'thunder_cloud_and_rain': '⛈️',
    'lightning': '🌩️',
    'snow_cloud': '🌨️',
    'snowman': '⛄',
    'snowman_without_snow': '⚛️',
    'snowflake': '❄️',
    'wind_blowing_face': '🌬️',
    'dash': '💨',
    'tornado': '🌪️',
    'fog': '🌫️',
    'umbrella': '☂️',
    'umbrella_with_rain_drops': '☔',
    'droplet': '💧',
    'sweat_drops': '💦',
    'ocean': '🌊',

    // Food & Drink
    'green_apple': '🍏',
    'apple': '🍎',
    'pear': '🍐',
    'tangerine': '🍊',
    'lemon': '🍋',
    'banana': '🍌',
    'watermelon': '🍉',
    'grapes': '🍇',
    'strawberry': '🍓',
    'melon': '🍈',
    'cherries': '🍒',
    'peach': '🍑',
    'pineapple': '🍍',
    'kiwifruit': '🥝',
    'avocado': '🥑',
    'tomato': '🍅',
    'eggplant': '🍆',
    'cucumber': '🥒',
    'carrot': '🥕',
    'corn': '🌽',
    'hot_pepper': '🌶️',
    'potato': '🥔',
    'sweet_potato': '🍠',
    'chestnut': '🌰',
    'peanuts': '🥜',
    'honey_pot': '🍯',
    'bread': '🍞',
    'croissant': '🥐',
    'baguette_bread': '🥖',
    'pretzel': '🥨',
    'cheese_wedge': '🧀',
    'egg': '🥚',
    'fried_egg': '🍳',
    'bacon': '🥓',
    'pancakes': '🥞',
    'fried_shrimp': '🍤',
    'poultry_leg': '🍗',
    'meat_on_bone': '🍖',
    'pizza': '🍕',
    'hotdog': '🌭',
    'hamburger': '🍔',
    'fries': '🍟',
    'taco': '🌮',
    'burrito': '🌯',
    'stuffed_flatbread': '🥙',
    'salad': '🥗',
    'shallow_pan_of_food': '🥘',
    'spaghetti': '🍝',
    'ramen': '🍜',
    'stew': '🍲',
    'curry': '🍛',
    'sushi': '🍣',
    'bento': '🍱',
    'dumpling': '🥟',
    'oden': '🍢',
    'shaved_ice': '🍧',
    'ice_cream': '🍨',
    'icecream': '🍦',
    'cake': '🍰',
    'birthday': '🎂',
    'pie': '🥧',
    'chocolate_bar': '🍫',
    'candy': '🍬',
    'lollipop': '🍭',
    'custard': '🍮',
    'doughnut': '🍩',
    'cookie': '🍪',
    'milk_glass': '🥛',
    'beer': '🍺',
    'beers': '🍻',
    'wine_glass': '🍷',
    'cocktail': '🍸',
    'tropical_drink': '🍹',
    'champagne': '🍾',
    'sake': '🍶',
    'tea': '🍵',
    'coffee': '☕',
    'baby_bottle': '🍼',
    'fork_and_knife': '🍴',
    'knife_fork_plate': '🍽️',

    // Activities & Sports
    'soccer': '⚽',
    'basketball': '🏀',
    'football': '🏈',
    'baseball': '⚾',
    'tennis': '🎾',
    'volleyball': '🏐',
    'rugby_football': '🏉',
    '8ball': '🎱',
    'ping_pong': '🏓',
    'badminton': '🏸',
    'goal_net': '🥅',
    'ice_hockey_stick_and_puck': '🏒',
    'field_hockey_stick_and_ball': '🏑',
    'cricket_bat_and_ball': '🏏',
    'golf': '⛳',
    'bow_and_arrow': '🏹',
    'fishing_pole_and_fish': '🎣',
    'boxing_glove': '🥊',
    'martial_arts_uniform': '🥋',
    'trophy': '🏆',
    'medal': '🏅',
    'first_place_medal': '🥇',
    'second_place_medal': '🥈',
    'third_place_medal': '🥉',
    'dart': '🎯',
    'video_game': '🎮',
    'game_die': '🎲',
    'spades': '♠️',
    'hearts': '♥️',
    'diamonds': '♦️',
    'clubs': '♣️',
    'black_joker': '🃏',
    'mahjong': '🀄',
    'flower_playing_cards': '🎴',
    'art': '🎨',
    'performing_arts': '🎭',

    // Travel & Places
    'car': '🚗',
    'taxi': '🚕',
    'blue_car': '🚙',
    'bus': '🚌',
    'trolleybus': '🚎',
    'racing_car': '🏎️',
    'police_car': '🚓',
    'ambulance': '🚑',
    'fire_engine': '🚒',
    'minibus': '🚐',
    'truck': '🚚',
    'articulated_lorry': '🚛',
    'tractor': '🚜',
    'scooter': '🛴',
    'bike': '🚲',
    'motor_scooter': '🛵',
    'motorcycle': '🏍️',
    'rotating_light': '🚨',
    'oncoming_police_car': '🚔',
    'oncoming_bus': '🚍',
    'oncoming_automobile': '🚘',
    'oncoming_taxi': '🚖',
    'aerial_tramway': '🚡',
    'mountain_cableway': '🚠',
    'suspension_railway': '🚟',
    'railway_car': '🚃',
    'train': '🚋',
    'monorail': '🚝',
    'bullettrain_side': '🚄',
    'bullettrain_front': '🚅',
    'light_rail': '🚈',
    'mountain_railway': '🚞',
    'steam_locomotive': '🚂',
    'train2': '🚆',
    'metro': '🚇',
    'tram': '🚊',
    'station': '🚉',
    'helicopter': '🚁',
    'small_airplane': '🛩️',
    'airplane': '✈️',
    'flight_departure': '🛫',
    'flight_arrival': '🛬',
    'rocket': '🚀',
    'satellite': '🛰️',
    'seat': '💺',
    'canoe': '🛶',
    'boat': '⛵',
    'motor_boat': '🛥️',
    'speedboat': '🚤',
    'passenger_ship': '🛳️',
    'ferry': '⛴️',
    'ship': '🚢',
    'anchor': '⚓',
    'construction': '🚧',
    'fuelpump': '⛽',
    'busstop': '🚏',
    'vertical_traffic_light': '🚦',
    'traffic_light': '🚥',
    'world_map': '🗺️',
    'moyai': '🗿',
    'statue_of_liberty': '🗽',
    'fountain': '⛲',
    'tokyo_tower': '🗼',
    'european_castle': '🏰',
    'stadium': '🏟️',
    'ferris_wheel': '🎡',
    'roller_coaster': '🎢',
    'carousel_horse': '🎠',
    'umbrella_on_ground': '⛱️',
    'beach_with_umbrella': '🏖️',
    'desert_island': '🏝️',
    'mountain': '⛰️',
    'snow_capped_mountain': '🏔️',
    'mount_fuji': '🗻',
    'volcano': '🌋',
    'desert': '🏜️',
    'camping': '🏕️',
    'tent': '⛺',
    'house': '🏠',
    'house_with_garden': '🏡',
    'office': '🏢',
    'post_office': '🏣',
    'european_post_office': '🏤',
    'hospital': '🏥',
    'bank': '🏦',
    'hotel': '🏨',
    'convenience_store': '🏪',
    'school': '🏫',
    'department_store': '🏬',
    'factory': '🏭',
    'japanese_castle': '🏯',
    'love_hotel': '🏩',
    'wedding': '💒',
    'classical_building': '🏛️',
    'church': '⛪',
    'mosque': '🕌',
    'synagogue': '🕍',
    'kaaba': '🕋',
    'shinto_shrine': '⛩️',

    // Objects
    'watch': '⌚',
    'iphone': '📱',
    'calling': '📲',
    'computer': '💻',
    'keyboard': '⌨️',
    'desktop_computer': '🖥️',
    'printer': '🖨️',
    'three_button_mouse': '🖱️',
    'trackball': '🖲️',
    'joystick': '🕹️',
    'clamp': '🗜️',
    'minidisc': '💽',
    'floppy_disk': '💾',
    'cd': '💿',
    'dvd': '📀',
    'vhs': '📼',
    'camera': '📷',
    'camera_with_flash': '📸',
    'video_camera': '📹',
    'movie_camera': '🎥',
    'film_projector': '📽️',
    'film_frames': '🎞️',
    'telephone_receiver': '📞',
    'phone': '☎️',
    'pager': '📟',
    'fax': '📠',
    'tv': '📺',
    'radio': '📻',
    'microphone': '🎤',
    'level_slider': '🎚️',
    'control_knobs': '🎛️',
    'stopwatch': '⏱️',
    'timer_clock': '⏲️',
    'alarm_clock': '⏰',
    'mantelpiece_clock': '🕰️',
    'hourglass_flowing_sand': '⏳',
    'hourglass': '⌛',
    'satellite_antenna': '📡',
    'battery': '🔋',
    'electric_plug': '🔌',
    'bulb': '💡',
    'flashlight': '🔦',
    'candle': '🕯️',
    'wastebasket': '🗑️',
    'oil_drum': '🛢️',
    'money_with_wings': '💸',
    'dollar': '💵',
    'yen': '💴',
    'euro': '💶',
    'pound': '💷',
    'moneybag': '💰',
    'credit_card': '💳',
    'gem': '💎',
    'scales': '⚖️',
    'wrench': '🔧',
    'hammer': '🔨',
    'hammer_and_pick': '⚒️',
    'hammer_and_wrench': '🛠️',
    'pick': '⛏️',
    'nut_and_bolt': '🔩',
    'gear': '⚙️',
    'chains': '⛓️',
    'gun': '🔫',
    'bomb': '💣',
    'knife': '🔪',
    'dagger_knife': '🗡️',
    'crossed_swords': '⚔️',
    'shield': '🛡️',
    'smoking': '🚬',
    'coffin': '⚰️',
    'funeral_urn': '⚱️',
    'amphora': '🏺',
    'crystal_ball': '🔮',
    'prayer_beads': '📿',
    'barber': '💈',
    'alembic': '⚗️',
    'telescope': '🔭',
    'microscope': '🔬',
    'hole': '🕳️',
    'pill': '💊',
    'syringe': '💉',
    'thermometer': '🌡️',
    'toilet': '🚽',
    'shower': '🚿',
    'bathtub': '🛁',
    'bath': '🛀',
    'bellhop_bell': '🛎️',
    'key': '🔑',
    'old_key': '🗝️',
    'door': '🚪',
    'couch_and_lamp': '🛋️',
    'bed': '🛏️',
    'sleeping_accommodation': '🛌',
    'frame_with_picture': '🖼️',
    'shopping_bags': '🛍️',
    'shopping_trolley': '🛒',
    'gift': '🎁',
    'balloon': '🎈',
    'flags': '🎏',
    'ribbon': '🎀',
    'confetti_ball': '🎊',
    'tada': '🎉',
    'dolls': '🎎',
    'izakaya_lantern': '🏮',
    'wind_chime': '🎐',
    'envelope': '✉️',
    'email': '📧',
    'love_letter': '💌',
    'inbox_tray': '📥',
    'outbox_tray': '📤',
    'package': '📦',
    'label': '🏷️',
    'mailbox_closed': '📪',
    'mailbox': '📫',
    'mailbox_with_mail': '📬',
    'mailbox_with_no_mail': '📭',
    'postbox': '📮',
    'postal_horn': '📯',
    'scroll': '📜',
    'page_with_curl': '📃',
    'page_facing_up': '📄',
    'bookmark_tabs': '📑',
    'bar_chart': '📊',
    'chart_with_upwards_trend': '📈',
    'chart_with_downwards_trend': '📉',
    'spiral_note_pad': '🗒️',
    'spiral_calendar_pad': '🗓️',
    'calendar': '📆',
    'date': '📅',
    'card_index': '📇',
    'card_file_box': '🗃️',
    'ballot_box_with_ballot': '🗳️',
    'file_cabinet': '🗄️',
    'clipboard': '📋',
    'file_folder': '📁',
    'open_file_folder': '📂',
    'card_index_dividers': '🗂️',
    'rolled_up_newspaper': '🗞️',
    'newspaper': '📰',
    'notebook': '📓',
    'notebook_with_decorative_cover': '📔',
    'ledger': '📒',
    'closed_book': '📕',
    'green_book': '📗',
    'blue_book': '📘',
    'orange_book': '📙',
    'books': '📚',
    'book': '📖',
    'bookmark': '🔖',
    'link': '🔗',
    'paperclip': '📎',
    'linked_paperclips': '🖇️',
    'triangular_ruler': '📐',
    'straight_ruler': '📏',
    'pushpin': '📌',
    'round_pushpin': '📍',
    'scissors': '✂️',
    'pen_ballpoint': '🖊️',
    'pen_fountain': '🖋️',
    'black_nib': '✒️',
    'paintbrush': '🖌️',
    'crayon': '🖍️',
    'pencil': '📝',
    'pencil2': '✏️',
    'mag': '🔍',
    'mag_right': '🔎',
    'lock_with_ink_pen': '🔏',
    'closed_lock_with_key': '🔐',
    'lock': '🔒',
    'unlock': '🔓',

    // Symbols
    'heart': '❤️',
    'orange_heart': '🧡',
    'yellow_heart': '💛',
    'green_heart': '💚',
    'blue_heart': '💙',
    'purple_heart': '💜',
    'black_heart': '🖤',
    'broken_heart': '💔',
    'heart_exclamation': '❣️',
    'two_hearts': '💕',
    'revolving_hearts': '💞',
    'heartbeat': '💓',
    'heartpulse': '💗',
    'sparkling_heart': '💖',
    'cupid': '💘',
    'gift_heart': '💝',
    'heart_decoration': '💟',
    'peace_symbol': '☮️',
    'cross': '✝️',
    'star_and_crescent': '☪️',
    'om_symbol': '🕉️',
    'wheel_of_dharma': '☸️',
    'star_of_david': '✡️',
    'six_pointed_star': '🔯',
    'menorah': '🕎',
    'yin_yang': '☯️',
    'orthodox_cross': '☦️',
    'place_of_worship': '🛐',
    'ophiuchus': '⛎',
    'aries': '♈',
    'taurus': '♉',
    'gemini': '♊',
    'cancer': '♋',
    'leo': '♌',
    'virgo': '♍',
    'libra': '♎',
    'scorpius': '♏',
    'sagittarius': '♐',
    'capricorn': '♑',
    'aquarius': '♒',
    'pisces': '♓',
    'id': '🆔',
    'atom_symbol': '⚛️',
    'accept': '🉑',
    'radioactive_sign': '☢️',
    'biohazard_sign': '☣️',
    'mobile_phone_off': '📴',
    'vibration_mode': '📳',
    'u6709': '🈶',
    'u7121': '🈚',
    'u7533': '🈸',
    'u55b6': '🈺',
    'u6708': '🈷️',
    'eight_pointed_black_star': '✴️',
    'vs': '🆚',
    'white_flower': '💮',
    'ideograph_advantage': '🉐',
    'secret': '㊙️',
    'congratulations': '㊗️',
    'u5408': '🈴',
    'u6e80': '🈵',
    'u5272': '🈹',
    'u7981': '🈲',
    'a': '🅰️',
    'b': '🅱️',
    'ab': '🆎',
    'cl': '🆑',
    'o2': '🅾️',
    'sos': '🆘',
    'x': '❌',
    'o': '⭕',
    'octagonal_sign': '🛑',
    'no_entry': '⛔',
    'name_badge': '📛',
    'no_entry_sign': '🚫',
    '100': '💯',
    'anger': '💢',
    'hotsprings': '♨️',
    'no_pedestrians': '🚷',
    'do_not_litter': '🚯',
    'no_bicycles': '🚳',
    'non-potable_water': '🚱',
    'underage': '🔞',
    'no_mobile_phones': '📵',
    'no_smoking': '🚭',
    'exclamation': '❗',
    'grey_exclamation': '❕',
    'question': '❓',
    'grey_question': '❔',
    'bangbang': '‼️',
    'interrobang': '⁉️',
    'low_brightness': '🔅',
    'high_brightness': '🔆',
    'part_alternation_mark': '〽️',
    'warning': '⚠️',
    'children_crossing': '🚸',
    'trident': '🔱',
    'fleur_de_lis': '⚜️',
    'beginner': '🔰',
    'recycle': '♻️',
    'white_check_mark': '✅',
    'chart': '💹',
    'sparkle': '❇️',
    'eight_spoked_asterisk': '✳️',
    'negative_squared_cross_mark': '❎',
    'globe_with_meridians': '🌐',
    'm': 'Ⓜ️',
    'cyclone': '🌀',
    'zzz': '💤',
    'atm': '🏧',
    'wc': '🚾',
    'wheelchair': '♿',
    'parking': '🅿️',
    'potable_water': '🚰',
    'mens': '🚹',
    'womens': '🚺',
    'baby_symbol': '🚼',
    'restroom': '🚻',
    'put_litter_in_its_place': '🚮',
    'cinema': '🎦',
    'signal_strength': '📶',
    'koko': '🈁',
    'symbols': '🔣',
    'information_source': 'ℹ️',
    'abc': '🔤',
    'abcd': '🔡',
    'capital_abcd': '🔠',
    'ng': '🆖',
    'ok': '🆗',
    'up': '🆙',
    'cool': '🆒',
    'new': '🆕',
    'free': '🆓',
    'zero': '0️⃣',
    'one': '1️⃣',
    'two': '2️⃣',
    'three': '3️⃣',
    'four': '4️⃣',
    'five': '5️⃣',
    'six': '6️⃣',
    'seven': '7️⃣',
    'eight': '8️⃣',
    'nine': '9️⃣',
    'keycap_ten': '🔟',
    '1234': '🔢',
    'hash': '#️⃣',
    'asterisk': '*️⃣',
    'arrow_forward': '▶️',
    'pause_button': '⏸️',
    'play_or_pause_button': '⏯️',
    'stop_button': '⏹️',
    'record_button': '⏺️',
    'track_next': '⏭️',
    'track_previous': '⏮️',
    'fast_forward': '⏩',
    'rewind': '⏪',
    'arrow_double_up': '⏫',
    'arrow_double_down': '⏬',
    'arrow_backward': '◀️',
    'arrow_up_small': '🔼',
    'arrow_down_small': '🔽',
    'arrow_right': '➡️',
    'arrow_left': '⬅️',
    'arrow_up': '⬆️',
    'arrow_down': '⬇️',
    'arrow_upper_right': '↗️',
    'arrow_lower_right': '↘️',
    'arrow_lower_left': '↙️',
    'arrow_upper_left': '↖️',
    'arrow_up_down': '↕️',
    'left_right_arrow': '↔️',
    'arrow_right_hook': '↪️',
    'leftwards_arrow_with_hook': '↩️',
    'arrow_heading_up': '⤴️',
    'arrow_heading_down': '⤵️',
    'twisted_rightwards_arrows': '🔀',
    'repeat': '🔁',
    'repeat_one': '🔂',
    'arrows_counterclockwise': '🔄',
    'arrows_clockwise': '🔃',
    'musical_note': '🎵',
    'notes': '🎶',
    'heavy_plus_sign': '➕',
    'heavy_minus_sign': '➖',
    'heavy_division_sign': '➗',
    'heavy_multiplication_x': '✖️',
    'infinity': '♾️',
    'heavy_dollar_sign': '💲',
    'currency_exchange': '💱',
    'tm': '™️',
    'copyright': '©️',
    'registered': '®️',
    'wavy_dash': '〰️',
    'curly_loop': '➰',
    'loop': '➿',
    'end': '🔚',
    'back': '🔙',
    'on': '🔛',
    'top': '🔝',
    'soon': '🔜',
    'heavy_check_mark': '✔️',
    'ballot_box_with_check': '☑️',
    'white_circle': '⚪',
    'black_circle': '⚫',
    'red_circle': '🔴',
    'large_blue_circle': '🔵',
    'small_orange_diamond': '🔸',
    'small_blue_diamond': '🔹',
    'small_red_triangle': '🔺',
    'small_red_triangle_down': '🔻',
    'diamond_shape_with_a_dot_inside': '💠',
    'radio_button': '🔘',
    'white_square_button': '🔳',
    'black_square_button': '🔲',
    'checkered_flag': '🏁',
    'triangular_flag_on_post': '🚩',
    'crossed_flags': '🎌',
    'flag_black': '🏴',
    'flag_white': '🏳️',
    'rainbow_flag': '🏳️‍🌈',
    'pirate_flag': '🏴‍☠️',

    // Country flags (selection)
    'flag_ac': '🇦🇨',
    'flag_ad': '🇦🇩',
    'flag_ae': '🇦🇪',
    'flag_af': '🇦🇫',
    'flag_ag': '🇦🇬',
    'flag_ai': '🇦🇮',
    'flag_al': '🇦🇱',
    'flag_am': '🇦🇲',
    'flag_ao': '🇦🇴',
    'flag_aq': '🇦🇶',
    'flag_ar': '🇦🇷',
    'flag_as': '🇦🇸',
    'flag_at': '🇦🇹',
    'flag_au': '🇦🇺',
    'flag_aw': '🇦🇼',
    'flag_ax': '🇦🇽',
    'flag_az': '🇦🇿',
    'flag_ba': '🇧🇦',
    'flag_bb': '🇧🇧',
    'flag_bd': '🇧🇩',
    'flag_be': '🇧🇪',
    'flag_bf': '🇧🇫',
    'flag_bg': '🇧🇬',
    'flag_bh': '🇧🇭',
    'flag_bi': '🇧🇮',
    'flag_bj': '🇧🇯',
    'flag_bl': '🇧🇱',
    'flag_bm': '🇧🇲',
    'flag_bn': '🇧🇳',
    'flag_bo': '🇧🇴',
    'flag_bq': '🇧🇶',
    'flag_br': '🇧🇷',
    'flag_bs': '🇧🇸',
    'flag_bt': '🇧🇹',
    'flag_bv': '🇧🇻',
    'flag_bw': '🇧🇼',
    'flag_by': '🇧🇾',
    'flag_bz': '🇧🇿',
    'flag_ca': '🇨🇦',
    'flag_cc': '🇨🇨',
    'flag_cd': '🇨🇩',
    'flag_cf': '🇨🇫',
    'flag_cg': '🇨🇬',
    'flag_ch': '🇨🇭',
    'flag_ci': '🇨🇮',
    'flag_ck': '🇨🇰',
    'flag_cl': '🇨🇱',
    'flag_cm': '🇨🇲',
    'flag_cn': '🇨🇳',
    'flag_co': '🇨🇴',
    'flag_cp': '🇨🇵',
    'flag_cr': '🇨🇷',
    'flag_cu': '🇨🇺',
    'flag_cv': '🇨🇻',
    'flag_cw': '🇨🇼',
    'flag_cx': '🇨🇽',
    'flag_cy': '🇨🇾',
    'flag_cz': '🇨🇿',
    'flag_de': '🇩🇪',
    'flag_dg': '🇩🇬',
    'flag_dj': '🇩🇯',
    'flag_dk': '🇩🇰',
    'flag_dm': '🇩🇲',
    'flag_do': '🇩🇴',
    'flag_dz': '🇩🇿',
    'flag_ea': '🇪🇦',
    'flag_ec': '🇪🇨',
    'flag_ee': '🇪🇪',
    'flag_eg': '🇪🇬',
    'flag_eh': '🇪🇭',
    'flag_er': '🇪🇷',
    'flag_es': '🇪🇸',
    'flag_et': '🇪🇹',
    'flag_eu': '🇪🇺',
    'flag_fi': '🇫🇮',
    'flag_fj': '🇫🇯',
    'flag_fk': '🇫🇰',
    'flag_fm': '🇫🇲',
    'flag_fo': '🇫🇴',
    'flag_fr': '🇫🇷',
    'flag_ga': '🇬🇦',
    'flag_gb': '🇬🇧',
    'flag_gd': '🇬🇩',
    'flag_ge': '🇬🇪',
    'flag_gf': '🇬🇫',
    'flag_gg': '🇬🇬',
    'flag_gh': '🇬🇭',
    'flag_gi': '🇬🇮',
    'flag_gl': '🇬🇱',
    'flag_gm': '🇬🇲',
    'flag_gn': '🇬🇳',
    'flag_gp': '🇬🇵',
    'flag_gq': '🇬🇶',
    'flag_gr': '🇬🇷',
    'flag_gs': '🇬🇸',
    'flag_gt': '🇬🇹',
    'flag_gu': '🇬🇺',
    'flag_gw': '🇬🇼',
    'flag_gy': '🇬🇾',
    'flag_hk': '🇭🇰',
    'flag_hm': '🇭🇲',
    'flag_hn': '🇭🇳',
    'flag_hr': '🇭🇷',
    'flag_ht': '🇭🇹',
    'flag_hu': '🇭🇺',
    'flag_ic': '🇮🇨',
    'flag_id': '🇮🇩',
    'flag_ie': '🇮🇪',
    'flag_il': '🇮🇱',
    'flag_im': '🇮🇲',
    'flag_in': '🇮🇳',
    'flag_io': '🇮🇴',
    'flag_iq': '🇮🇶',
    'flag_ir': '🇮🇷',
    'flag_is': '🇮🇸',
    'flag_it': '🇮🇹',
    'flag_je': '🇯🇪',
    'flag_jm': '🇯🇲',
    'flag_jo': '🇯🇴',
    'flag_jp': '🇯🇵',
    'flag_ke': '🇰🇪',
    'flag_kg': '🇰🇬',
    'flag_kh': '🇰🇭',
    'flag_ki': '🇰🇮',
    'flag_km': '🇰🇲',
    'flag_kn': '🇰🇳',
    'flag_kp': '🇰🇵',
    'flag_kr': '🇰🇷',
    'flag_kw': '🇰🇼',
    'flag_ky': '🇰🇾',
    'flag_kz': '🇰🇿',
    'flag_la': '🇱🇦',
    'flag_lb': '🇱🇧',
    'flag_lc': '🇱🇨',
    'flag_li': '🇱🇮',
    'flag_lk': '🇱🇰',
    'flag_lr': '🇱🇷',
    'flag_ls': '🇱🇸',
    'flag_lt': '🇱🇹',
    'flag_lu': '🇱🇺',
    'flag_lv': '🇱🇻',
    'flag_ly': '🇱🇾',
    'flag_ma': '🇲🇦',
    'flag_mc': '🇲🇨',
    'flag_md': '🇲🇩',
    'flag_me': '🇲🇪',
    'flag_mf': '🇲🇫',
    'flag_mg': '🇲🇬',
    'flag_mh': '🇲🇭',
    'flag_mk': '🇲🇰',
    'flag_ml': '🇲🇱',
    'flag_mm': '🇲🇲',
    'flag_mn': '🇲🇳',
    'flag_mo': '🇲🇴',
    'flag_mp': '🇲🇵',
    'flag_mq': '🇲🇶',
    'flag_mr': '🇲🇷',
    'flag_ms': '🇲🇸',
    'flag_mt': '🇲🇹',
    'flag_mu': '🇲🇺',
    'flag_mv': '🇲🇻',
    'flag_mw': '🇲🇼',
    'flag_mx': '🇲🇽',
    'flag_my': '🇲🇾',
    'flag_mz': '🇲🇿',
    'flag_na': '🇳🇦',
    'flag_nc': '🇳🇨',
    'flag_ne': '🇳🇪',
    'flag_nf': '🇳🇫',
    'flag_ng': '🇳🇬',
    'flag_ni': '🇳🇮',
    'flag_nl': '🇳🇱',
    'flag_no': '🇳🇴',
    'flag_np': '🇳🇵',
    'flag_nr': '🇳🇷',
    'flag_nu': '🇳🇺',
    'flag_nz': '🇳🇿',
    'flag_om': '🇴🇲',
    'flag_pa': '🇵🇦',
    'flag_pe': '🇵🇪',
    'flag_pf': '🇵🇫',
    'flag_pg': '🇵🇬',
    'flag_ph': '🇵🇭',
    'flag_pk': '🇵🇰',
    'flag_pl': '🇵🇱',
    'flag_pm': '🇵🇲',
    'flag_pn': '🇵🇳',
    'flag_pr': '🇵🇷',
    'flag_ps': '🇵🇸',
    'flag_pt': '🇵🇹',
    'flag_pw': '🇵🇼',
    'flag_py': '🇵🇾',
    'flag_qa': '🇶🇦',
    'flag_re': '🇷🇪',
    'flag_ro': '🇷🇴',
    'flag_rs': '🇷🇸',
    'flag_ru': '🇷🇺',
    'flag_rw': '🇷🇼',
    'flag_sa': '🇸🇦',
    'flag_sb': '🇸🇧',
    'flag_sc': '🇸🇨',
    'flag_sd': '🇸🇩',
    'flag_se': '🇸🇪',
    'flag_sg': '🇸🇬',
    'flag_sh': '🇸🇭',
    'flag_si': '🇸🇮',
    'flag_sj': '🇸🇯',
    'flag_sk': '🇸🇰',
    'flag_sl': '🇸🇱',
    'flag_sm': '🇸🇲',
    'flag_sn': '🇸🇳',
    'flag_so': '🇸🇴',
    'flag_sr': '🇸🇷',
    'flag_ss': '🇸🇸',
    'flag_st': '🇸🇹',
    'flag_sv': '🇸🇻',
    'flag_sx': '🇸🇽',
    'flag_sy': '🇸🇾',
    'flag_sz': '🇸🇿',
    'flag_ta': '🇹🇦',
    'flag_tc': '🇹🇨',
    'flag_td': '🇹🇩',
    'flag_tf': '🇹🇫',
    'flag_tg': '🇹🇬',
    'flag_th': '🇹🇭',
    'flag_tj': '🇹🇯',
    'flag_tk': '🇹🇰',
    'flag_tl': '🇹🇱',
    'flag_tm': '🇹🇲',
    'flag_tn': '🇹🇳',
    'flag_to': '🇹🇴',
    'flag_tr': '🇹🇷',
    'flag_tt': '🇹🇹',
    'flag_tv': '🇹🇻',
    'flag_tw': '🇹🇼',
    'flag_tz': '🇹🇿',
    'flag_ua': '🇺🇦',
    'flag_ug': '🇺🇬',
    'flag_um': '🇺🇲',
    'flag_us': '🇺🇸',
    'flag_uy': '🇺🇾',
    'flag_uz': '🇺🇿',
    'flag_va': '🇻🇦',
    'flag_vc': '🇻🇨',
    'flag_ve': '🇻🇪',
    'flag_vg': '🇻🇬',
    'flag_vi': '🇻🇮',
    'flag_vn': '🇻🇳',
    'flag_vu': '🇻🇺',
    'flag_wf': '🇼🇫',
    'flag_ws': '🇼🇸',
    'flag_xk': '🇽🇰',
    'flag_ye': '🇾🇪',
    'flag_yt': '🇾🇹',
    'flag_za': '🇿🇦',
    'flag_zm': '🇿🇲',
    'flag_zw': '🇿🇼',
};

/**
 * Converts Discord-style emoji codes (e.g., :skull:, :nerd_face:) to Unicode emojis
 * @param {string} text - The text containing Discord emoji codes
 * @returns {string} - The text with emoji codes replaced by Unicode emojis
 */
function convertEmojis(text) {
    return text.replace(/:([a-zA-Z0-9_+-]+):/g, (match, emojiCode) => {
        return emojiMap[emojiCode] || match;
    });
}


/**
 * Fetch account details from accounts.json by username.
 * @param username Username of the account to fetch
 * @returns {Promise<Object|boolean>} Account object or false if not found/error
 */
async function getAccount(username) {
    try {
        const data = await fs.promises.readFile('config/accounts.json', 'utf8');
        const accounts = JSON.parse(data);

        if (!accounts || !Array.isArray(accounts) || accounts.length === 0) {
            return undefined;
        }
        
        const account = accounts.find(acc => acc.username === username);
        if (!account) {
            return undefined;
        }
        
        return account;
    } catch (error) {
        console.error('Error reading accounts.json:', error);
        return undefined;
    }
}


/**
 * Check if a file exist, if not create it
 * @param filePath Path
 */
function checkAndCreateFile(filePath) {
    const dir = path.dirname(filePath);
    const initialContent = '';

    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
        console.log('Directory created:', dir);
    }

    if (!fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, initialContent);
        console.log('File created:', filePath);
    }
}


/**
 * Overwrite a file
 * @param filePath Path
 * @param content Content
 * @returns {Promise<void>} Status
 */
async function writeToFile(filePath, content) {
    try {
        await fs.writeFile(filePath, content);
        console.log('File written successfully');
    } catch (error) {
        console.error('Error writing file:', error);
    }
}


/**
 * Write data to a file
 * @param filePath Path
 * @param content Content
 * @returns {Promise<void>} Status
 */
async function appendToFile(filePath, content) {
    try {
        await fs.appendFile(filePath, content);
        console.log('Content appended');
    } catch (error) {
        console.error('Error appending:', error);
    }
}


/**
 * Get the leader bot's username
 * @returns {Promise<*|boolean>} Status
 */
async function getLeader() {
    try {
        const data = await fs.promises.readFile('config/accounts.json', 'utf8');
        const accounts = JSON.parse(data);

        if (!accounts || accounts.length === 0) {
            return false;
        }

        const leader = accounts.find(acc => acc.leader === true);
        if (!leader) return false;
        return leader.username;
    } catch (error)  {
        return false;
    }
}


/**
 * Check if a user has the required permission level for an account.
 *
 * Level 1: Admin - Full access
 * Level 2: Moderator - Standard access
 * Level 3: Users - Basic access
 * @param username Username to check
 * @param accountName Account name to check against
 * @param requiredLevel Required permission level (1, 2, or 3)
 * @param accountsData The accounts data array
 * @returns {Promise<boolean>} Has perms
 */
async function hasPermissions(username, accountName, requiredLevel) {
    const account = await getAccount(accountName);
    if (!account) return false;

    const usersGroup = account.permissions.find(perm => perm.level === 3);
    if (usersGroup && usersGroup.blacklisted && usersGroup.blacklisted.includes(username)) {
        return false;
    }

    let userLevel = null;

    for (const permission of account.permissions) {
        if (permission.players && permission.players.includes(username)) {
            userLevel = permission.level;
            break;
        }
    }

    if (userLevel === null) {
        userLevel = 3;
    }

    return userLevel <= requiredLevel;
}


/**
 * Get the permission level of a user for a specific account.
 * @param username Username to check
 * @param accountName Account name to check against  
 * @returns {Promise<number|null>} Permission level (1, 2, or 3) or null if not found
 */
async function getPermissionLevel(username, accountName) {
    const account = await getAccount(accountName);

    if (!account || !account.permissions) {
        return null;
    }
    
    for (const permission of account.permissions) {
        if (permission.blacklisted && Array.isArray(permission.blacklisted) && permission.blacklisted.includes(username)) {
            return 4; 
        }
    }
    
    let userLevel = null;

    for (const permission of account.permissions) {
        if (permission.players && permission.players.includes(username)) {
            userLevel = permission.level;
            break;
        }
    }
    
    return userLevel !== null ? userLevel : 3;
}

/**
 * Determines if the username is the targeted bot (for the !:username cmd prefix)
 * @param args The command args
 * @param username The username to check
 * @returns {boolean} Status
 */
function isCommandTarget(args, username) {
    if (args[0] && args[0].startsWith('!:')) {
        const targetUsername = args[0].substring(2); // Remove !: prefix
        return targetUsername === username;
    }

    return true;
}

export { hasPermissions, getPermissionLevel, getAccount, getLeader, isCommandTarget, checkAndCreateFile, writeToFile, appendToFile, convertEmojis };